// Sökbara synonymer från components/ProductSearch.tsx 2026-10-01. Flyttas till
// produkternas fält "Fler sökord" i Sanity av scripts/sanity/migrera.mjs.
export const SYNONYMS: Record<string,string> = {
 "fardig-grasmatta":"gras grasmatta pa rulle rullgras torv matta",
 "jord-i-sackar":"matjord planteringsjord sack odling plantera",
 "grasfrogodsel":"fro godning naring gazon",
 "marksten-betong-natursten":"sten uppfart garduppfart plattor granit",
 "gards-ganggrus":"grus singel makadam gang",
 "armering":"jarn nat betongjarn armeringsjarn",
 "betongcement":"cement betong gjuta gjutning",
 "leca":"lattklinker block murblock",
 "ved":"brasa braved bjork eldning",
 "pellets":"pellet uppvarmning",
 "varmeloggs":"briketter loggs eldning",
 "ror":"pvc ht muffror avlopp bojar grenror skarvmuff",
 "dranering":"dranering dransslang dagvatten fiberduk markduk trumma",
 "brunnar-betackningar":"brunn wavin stigarror jarnbetackning spygatt golvbrunn lock",
 "rannor-galler":"aco ranna spaltgaller avvattning galler linjeavvattning",
 "verktyg-handredskap":"slev murslev spackel borste skyffel skottkarra glattare verktyg",
 "gjutning-formning":"formror distanskloss najtrad visp murarbalja gjutform",
 "infastning-forbrukning":"spik plugg skruv krampa gangstang stolpsko byggplast sopsack storsack",
 "borr-kapning":"diamantborr diamantklinga kapskiva borra kapa",
 "golvbrunnar-ventiler":"golvbrunn ventil sotlucka spjall tallriksventil",
 "skydd-underhall":"platon putsnat ograsduk markduk handske borste",
 "ejder":"ejder vaghinder trafikavstangare trafikhinder betongsugga avstangare",
 "dekorsten":"prydnadssten rabattsten",
 "ocean":"rengoring stad tvatt",
};
